const images = {
    brandAdidas: require('~/assets/images/contain/brand_logo_Adidas.png'),
    brandAsics: require('~/assets/images/contain/brand_logo_Asics.png'),
    brandReebok: require('~/assets/images/contain/brand_logo_Reebok.png'),
    brandTimberland: require('~/assets/images/contain/brand_logo_Timberland.png'),
    brandUnderArmour: require('~/assets/images/contain/brand_logo_Under_Armour.png'),
    brandVans: require('~/assets/images/contain/brand_logo_Vans.png'),
    clip: require('~/assets/images/contain/clip.mp4'),
    defaultAvatar: require('~/assets/images/contain/default_user_avatar.png'),
    emptyBag: require('~/assets/images/contain/empty_bag.png'),
    facebook: require('~/assets/images/contain/facebook.svg').default,
    hero: require('~/assets/images/contain/hero.png'),
    highlight: require('~/assets/images/contain/highlight.png'),
    instagram: require('~/assets/images/contain/instagram.svg').default,
    menu: require('~/assets/images/contain/menu.svg').default,
    messenger: require('~/assets/images/contain/messenger.svg').default,
    nullRmb: require('~/assets/images/contain/null_rmb.png'),
    null: require('~/assets/images/contain/null.jpg'),
    shoe1: require('~/assets/images/contain/shoe1.png'),
    shoe2: require('~/assets/images/contain/shoe2.png'),
    shoe3: require('~/assets/images/contain/shoe3.png'),
    shoe4: require('~/assets/images/contain/shoe4.png'),
    shoe5: require('~/assets/images/contain/shoe5.png'),
    shoe6: require('~/assets/images/contain/shoe6.png'),
    shoe7: require('~/assets/images/contain/shoe7.png'),
    shoe8: require('~/assets/images/contain/shoe8.png'),
    shoe9: require('~/assets/images/contain/shoe9.png'),
    shoe10: require('~/assets/images/contain/shoe10.png'),
    shoe11: require('~/assets/images/contain/shoe11.png'),
    shoe12: require('~/assets/images/contain/shoe12.png'),
    shoe13: require('~/assets/images/contain/shoe13.png'),
    shoe14: require('~/assets/images/contain/shoe14.png'),
    shoe15: require('~/assets/images/contain/shoe15.png'),
    shoe16: require('~/assets/images/contain/shoe16.png'),
    shoe17: require('~/assets/images/contain/shoe17.png'),
    shoe18: require('~/assets/images/contain/shoe18.png'),
    shoe19: require('~/assets/images/contain/shoe19.png'),
    shoe20: require('~/assets/images/contain/shoe20.png'),
    logo: require('~/assets/images/contain/sole-mate_ai-logo.png'),
    twitter: require('~/assets/images/contain/twitter.svg').default,
    vCover1: require('~/assets/images/contain/vcover1.png'),
    vCover2: require('~/assets/images/contain/vcover2.png'),
    vCover3: require('~/assets/images/contain/vcover3.png'),
    youtube: require('~/assets/images/contain/youtube.svg').default,
};

export default images;
