import React from 'react';
import PropTypes from 'prop-types';

import {
    AddProductIcon,
    ArrowIcon,
    BasketIcon,
    CalendarIcon,
    CartIcon,
    CloseIcon,
    ClosedEyeIcon,
    CogIcon,
    CustomersIcon,
    DashboardIcon,
    DowntrendIcon,
    EyeIcon,
    FacebookIcon,
    GoogleIcon,
    GridIcon,
    HeartIcon,
    HistoryOrderIcon,
    InstagramIcon,
    ListIcon,
    LoadingIcon,
    MinusIcon,
    OptionsIcon,
    OrdersIcon,
    PlayIcon,
    PlusIcon,
    ProductsIcon,
    ProfitIcon,
    RemoveCartItemIcon,
    ReturnIcon,
    SearchIcon,
    SellPhoneLinkIcon,
    SendMessageIcon,
    ShippingIcon,
    SignOutIcon,
    SizeIcon,
    StatsIcon,
    TasksIcon,
    TotalItemsIcon,
    UptrendIcon,
    UsdIcon,
    UserIcon,
    WareHouseIcon,
} from '~/assets/icons';

const Icons = (props) => {
    const components = {
        historyOrder: HistoryOrderIcon,
        loading: LoadingIcon,
        calendar: CalendarIcon,
        sellPhoneLink: SellPhoneLinkIcon,
        products: ProductsIcon,
        orders: OrdersIcon,
        customersIcon: CustomersIcon,
        addProduct: AddProductIcon,
        arrow: ArrowIcon,
        basket: BasketIcon,
        cog: CogIcon,
        dashboard: DashboardIcon,
        uptrend: UptrendIcon,
        downtrend: DowntrendIcon,
        eye: EyeIcon,
        closedEye: ClosedEyeIcon,
        grid: GridIcon,
        list: ListIcon,
        options: OptionsIcon,
        search: SearchIcon,
        stats: StatsIcon,
        tasks: TasksIcon,
        usd: UsdIcon,
        user: UserIcon,
        google: GoogleIcon,
        facebook: FacebookIcon,
        instagram: InstagramIcon,
        cart: CartIcon,
        heart: HeartIcon,
        signOut: SignOutIcon,
        size: SizeIcon,
        shipping: ShippingIcon,
        return: ReturnIcon,
        play: PlayIcon,
        close: CloseIcon,
        sendMessage: SendMessageIcon,
        minus: MinusIcon,
        plus: PlusIcon,
        removeCartItem: RemoveCartItemIcon,
        cell_phone_link: SellPhoneLinkIcon,
        profit: ProfitIcon,
        warehouse: WareHouseIcon,
        total_items: TotalItemsIcon,
    };

    const IconComponent = components[props.icon];

    return <IconComponent ref={props.ref} {...props} />;
};

Icons.propTypes = {
    props: PropTypes.shape({
        icon: PropTypes.string.isRequired,
        width: PropTypes.number,
        height: PropTypes.number,
        color: PropTypes.string,
        onClick: PropTypes.func,
        className: PropTypes.string,
        iconRef: PropTypes.object,
    }),
};
Icons.defaultProps = {
    icon: 'heart',
    size: 24,
    color: '#a9aba7',
};

export default Icons;
